/**
 * Curated 50-recipe starter list seeded for every new coach.
 *
 * Distribution (per spec §6):
 *   Breakfast 12, Lunch 15, Dinner 15, Snacks 8.
 * Cuisine mix: ~60 % Pakistani/regional, ~40 % international.
 *
 * The seeder loops these definitions and inserts each as a `Recipe` row
 * stamped with the coach's `coachId`. `categorySlug` maps to the
 * coach-scoped `RecipeCategory` created earlier in the same seed pass
 * (breakfast / lunch / dinner / snacks / smoothies / high-protein /
 * meal-prep / desserts / salads / soups — see `seedCoachDefaults`).
 *
 * Macros are nutritional estimates per serving — they're round-number
 * realistic, not lab-precise. Coaches edit recipes after seeding.
 */

export type RecipeCategorySlug =
  | "breakfast"
  | "lunch"
  | "dinner"
  | "snacks"
  | "smoothies"
  | "desserts"
  | "salads"
  | "soups"
  | "meal-prep"
  | "high-protein";

export interface RecipeDef {
  slug: string;
  title: string;
  description: string;
  categorySlug: RecipeCategorySlug;
  /** Dietary tag slugs to attach. Must be a subset of the seeded tags. */
  tags?: string[];
  ingredients: string[];
  instructions: string[];
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  servings: number;
  prepTimeMins: number;
  cookTimeMins: number;
  /** True for Pakistani/regional dishes, false for international. Logged for reporting. */
  regional: boolean;
}

// ─── Breakfast (12) ────────────────────────────────────────────────

const BREAKFAST: RecipeDef[] = [
  {
    slug: "anda-paratha",
    title: "Anda Paratha",
    description: "Pakistani-style whole-wheat paratha stuffed with seasoned eggs.",
    categorySlug: "breakfast",
    tags: ["high-protein"],
    ingredients: [
      "1 whole-wheat paratha",
      "2 large eggs",
      "1/4 small onion, finely chopped",
      "1 green chilli, chopped",
      "Salt and black pepper to taste",
      "1 tsp ghee",
    ],
    instructions: [
      "Whisk eggs with onion, chilli, salt and pepper.",
      "Heat ghee in a non-stick pan and pour in the egg mixture.",
      "Cook on low heat, stirring gently, until just set.",
      "Wrap the eggs inside the warm paratha and serve.",
    ],
    calories: 420, protein: 22, carbs: 36, fat: 22,
    servings: 1, prepTimeMins: 5, cookTimeMins: 10,
    regional: true,
  },
  {
    slug: "halwa-puri-light",
    title: "Lighter Halwa Puri",
    description: "Slimmed-down weekend classic — chana, semolina halwa and one baked puri.",
    categorySlug: "breakfast",
    ingredients: [
      "1/2 cup boiled chana (chickpeas)",
      "1 small onion + 1 tomato",
      "1 tsp ghee",
      "2 tbsp semolina (sooji)",
      "1 tbsp sugar substitute",
      "1 baked (not fried) puri",
    ],
    instructions: [
      "Sauté onion and tomato in ghee with chana masala until soft.",
      "Add chickpeas with 1/4 cup water and simmer 5 minutes.",
      "Toast semolina with sugar substitute and a splash of milk until thick.",
      "Serve alongside the baked puri.",
    ],
    calories: 480, protein: 14, carbs: 70, fat: 14,
    servings: 1, prepTimeMins: 10, cookTimeMins: 15,
    regional: true,
  },
  {
    slug: "egg-bhurji-roti",
    title: "Egg Bhurji with Roti",
    description: "Spiced scrambled eggs with onion and tomato, served with two chapatis.",
    categorySlug: "breakfast",
    tags: ["high-protein"],
    ingredients: [
      "3 large eggs",
      "1/2 onion, chopped",
      "1 small tomato, chopped",
      "1/2 tsp red chilli powder",
      "1/4 tsp turmeric",
      "1 tbsp ghee",
      "2 whole-wheat rotis",
    ],
    instructions: [
      "Sauté onion in ghee until golden.",
      "Add tomato, spices and salt; cook until soft.",
      "Whisk in eggs and stir until just set.",
      "Serve hot with warm rotis.",
    ],
    calories: 460, protein: 26, carbs: 38, fat: 22,
    servings: 1, prepTimeMins: 5, cookTimeMins: 10,
    regional: true,
  },
  {
    slug: "oats-with-banana-honey",
    title: "Oats with Banana & Honey",
    description: "Creamy stovetop oats topped with sliced banana, honey and walnuts.",
    categorySlug: "breakfast",
    tags: ["vegetarian"],
    ingredients: [
      "1/2 cup rolled oats",
      "1 cup low-fat milk",
      "1 medium banana",
      "1 tbsp honey",
      "1 tbsp chopped walnuts",
      "Pinch of cinnamon",
    ],
    instructions: [
      "Bring milk to a gentle simmer in a small saucepan.",
      "Stir in oats and cook 4-5 minutes until creamy.",
      "Pour into a bowl, top with banana, honey, walnuts and cinnamon.",
    ],
    calories: 380, protein: 14, carbs: 60, fat: 9,
    servings: 1, prepTimeMins: 2, cookTimeMins: 6,
    regional: false,
  },
  {
    slug: "greek-yogurt-parfait",
    title: "Greek Yogurt Parfait",
    description: "Layered Greek yogurt, berries and granola — high protein, low fat.",
    categorySlug: "breakfast",
    tags: ["high-protein", "vegetarian"],
    ingredients: [
      "200 g 0 % Greek yogurt",
      "1/2 cup mixed berries",
      "3 tbsp granola",
      "1 tsp honey",
    ],
    instructions: [
      "Spoon half the yogurt into a glass.",
      "Top with half the berries and half the granola.",
      "Repeat layers and drizzle with honey.",
    ],
    calories: 290, protein: 22, carbs: 38, fat: 6,
    servings: 1, prepTimeMins: 5, cookTimeMins: 0,
    regional: false,
  },
  {
    slug: "protein-oatmeal-pancakes",
    title: "Protein Oatmeal Pancakes",
    description: "Blender pancakes from oats, banana, eggs and whey.",
    categorySlug: "breakfast",
    tags: ["high-protein"],
    ingredients: [
      "1/2 cup oats",
      "1 ripe banana",
      "2 eggs",
      "1 scoop vanilla whey",
      "1/2 tsp baking powder",
      "1 tsp coconut oil",
    ],
    instructions: [
      "Blend oats, banana, eggs, whey and baking powder until smooth.",
      "Heat coconut oil in a non-stick pan.",
      "Cook 1/4 cup batter at a time, 1-2 min each side.",
    ],
    calories: 410, protein: 32, carbs: 42, fat: 11,
    servings: 1, prepTimeMins: 5, cookTimeMins: 10,
    regional: false,
  },
  {
    slug: "aloo-paratha-light",
    title: "Lighter Aloo Paratha",
    description: "One whole-wheat aloo paratha cooked with minimal ghee, served with curd.",
    categorySlug: "breakfast",
    tags: ["vegetarian"],
    ingredients: [
      "1 medium boiled potato",
      "1/4 tsp red chilli powder",
      "1/4 tsp garam masala",
      "1 cup whole-wheat flour",
      "1 tsp ghee",
      "1/2 cup plain curd",
    ],
    instructions: [
      "Mash potato with chilli, garam masala and salt.",
      "Knead flour with water into soft dough; roll into a ball and stuff with the potato mix.",
      "Roll out gently and cook on a hot tawa with 1 tsp ghee, flipping until golden.",
      "Serve with curd.",
    ],
    calories: 430, protein: 13, carbs: 70, fat: 11,
    servings: 1, prepTimeMins: 10, cookTimeMins: 10,
    regional: true,
  },
  {
    slug: "masala-omelette-toast",
    title: "Masala Omelette & Toast",
    description: "Spiced 3-egg omelette with onion, tomato and coriander, plus two slices of whole-grain toast.",
    categorySlug: "breakfast",
    tags: ["high-protein"],
    ingredients: [
      "3 large eggs",
      "1/4 onion, chopped",
      "1/2 tomato, chopped",
      "1 tbsp coriander, chopped",
      "1 green chilli",
      "1 tsp olive oil",
      "2 slices whole-grain bread",
    ],
    instructions: [
      "Whisk eggs with all the vegetables and salt.",
      "Heat olive oil in a non-stick pan and pour in the mixture.",
      "Cook on low until just set; fold and slide onto a plate.",
      "Serve with toasted bread.",
    ],
    calories: 450, protein: 28, carbs: 30, fat: 22,
    servings: 1, prepTimeMins: 5, cookTimeMins: 7,
    regional: true,
  },
  {
    slug: "avocado-toast",
    title: "Avocado Toast",
    description: "Mashed avocado on sourdough with chilli flakes and lemon.",
    categorySlug: "breakfast",
    tags: ["vegetarian"],
    ingredients: [
      "1/2 ripe avocado",
      "1 tsp lemon juice",
      "2 slices sourdough",
      "Pinch of chilli flakes",
      "Pinch of sea salt",
    ],
    instructions: [
      "Mash avocado with lemon juice and salt.",
      "Toast sourdough until crisp.",
      "Spread avocado on top and finish with chilli flakes.",
    ],
    calories: 320, protein: 9, carbs: 38, fat: 16,
    servings: 1, prepTimeMins: 5, cookTimeMins: 3,
    regional: false,
  },
  {
    slug: "smoothie-bowl",
    title: "Berry Protein Smoothie Bowl",
    description: "Thick smoothie of frozen berries, banana, whey and oat milk, topped with seeds.",
    categorySlug: "smoothies",
    tags: ["high-protein", "vegetarian"],
    ingredients: [
      "1 cup frozen mixed berries",
      "1/2 banana",
      "1 scoop vanilla whey",
      "200 ml oat milk",
      "1 tbsp chia seeds",
    ],
    instructions: [
      "Blend berries, banana, whey and oat milk until thick.",
      "Pour into a bowl and top with chia seeds and a few extra berries.",
    ],
    calories: 360, protein: 30, carbs: 48, fat: 7,
    servings: 1, prepTimeMins: 5, cookTimeMins: 0,
    regional: false,
  },
  {
    slug: "lassi-with-whey",
    title: "Mango Lassi with Whey",
    description: "Mango lassi blended with vanilla whey for a high-protein breakfast.",
    categorySlug: "smoothies",
    tags: ["high-protein", "vegetarian"],
    ingredients: [
      "1/2 cup mango pulp",
      "200 g low-fat curd",
      "1 scoop vanilla whey",
      "1/4 tsp cardamom",
      "4 ice cubes",
    ],
    instructions: [
      "Blend mango, curd, whey, cardamom and ice until smooth.",
      "Pour into a tall glass and serve cold.",
    ],
    calories: 310, protein: 30, carbs: 38, fat: 4,
    servings: 1, prepTimeMins: 5, cookTimeMins: 0,
    regional: true,
  },
  {
    slug: "shami-kebab-paratha",
    title: "Shami Kebab Paratha",
    description: "Wholewheat paratha rolled with two homemade chicken shami kebabs.",
    categorySlug: "breakfast",
    tags: ["high-protein"],
    ingredients: [
      "2 chicken shami kebabs",
      "1 whole-wheat paratha (light ghee)",
      "1 tbsp mint chutney",
      "Sliced cucumber and onion",
    ],
    instructions: [
      "Warm the kebabs on a tawa for 2 min each side.",
      "Spread mint chutney on the paratha.",
      "Place kebabs, cucumber and onion in the centre; roll and serve.",
    ],
    calories: 480, protein: 32, carbs: 38, fat: 22,
    servings: 1, prepTimeMins: 5, cookTimeMins: 5,
    regional: true,
  },
];

// ─── Lunch (15) ────────────────────────────────────────────────────

const LUNCH: RecipeDef[] = [
  {
    slug: "chicken-karahi",
    title: "Chicken Karahi",
    description: "Quick wok-cooked chicken in tomato, ginger, chilli and yogurt.",
    categorySlug: "lunch",
    tags: ["high-protein"],
    ingredients: [
      "300 g boneless chicken, cubed",
      "2 tomatoes, chopped",
      "1 tbsp ginger-garlic paste",
      "1 tbsp yogurt",
      "1 green chilli",
      "1/2 tsp red chilli powder",
      "1/2 tsp garam masala",
      "1 tbsp oil",
    ],
    instructions: [
      "Sear chicken in oil for 4-5 min.",
      "Add ginger-garlic, then tomatoes; cook until oil separates.",
      "Stir in yogurt and spices; simmer 8-10 min.",
      "Top with green chilli and serve with roti.",
    ],
    calories: 480, protein: 45, carbs: 12, fat: 26,
    servings: 1, prepTimeMins: 10, cookTimeMins: 20,
    regional: true,
  },
  {
    slug: "chicken-biryani-portion",
    title: "Chicken Biryani (Portion-Controlled)",
    description: "Single-serving chicken biryani with basmati rice and yogurt raita.",
    categorySlug: "lunch",
    tags: ["high-protein"],
    ingredients: [
      "150 g chicken thigh",
      "3/4 cup basmati rice (cooked)",
      "1 tbsp biryani masala",
      "1 tomato",
      "2 tbsp yogurt",
      "1 tsp ghee",
      "100 g raita (yogurt + cucumber)",
    ],
    instructions: [
      "Marinate chicken in yogurt and masala for 15 min.",
      "Sear in ghee, add tomato and 1/4 cup water; cook 12 min.",
      "Layer over cooked rice and steam 2 min on low.",
      "Serve with raita.",
    ],
    calories: 560, protein: 38, carbs: 64, fat: 14,
    servings: 1, prepTimeMins: 20, cookTimeMins: 25,
    regional: true,
  },
  {
    slug: "daal-chawal",
    title: "Daal Chawal",
    description: "Yellow split lentil daal with steamed basmati rice and a tadka.",
    categorySlug: "lunch",
    tags: ["vegetarian", "high-protein"],
    ingredients: [
      "1/2 cup yellow daal",
      "1 small onion",
      "1 tomato",
      "1 tsp ginger-garlic paste",
      "1/2 tsp turmeric",
      "3/4 cup cooked basmati rice",
      "1 tsp ghee",
      "1 dry red chilli",
    ],
    instructions: [
      "Pressure cook daal with turmeric, onion, tomato and ginger-garlic.",
      "Heat ghee and crackle a tadka of red chilli and cumin.",
      "Pour the tadka over the daal and serve with rice.",
    ],
    calories: 420, protein: 18, carbs: 70, fat: 8,
    servings: 1, prepTimeMins: 5, cookTimeMins: 25,
    regional: true,
  },
  {
    slug: "chana-pulao",
    title: "Chana Pulao",
    description: "Spiced chickpea pulao with cumin, whole spices and a side salad.",
    categorySlug: "lunch",
    tags: ["vegetarian"],
    ingredients: [
      "1 cup cooked chickpeas",
      "1 cup basmati rice (cooked)",
      "1 small onion, sliced",
      "1 tsp cumin",
      "1 bay leaf",
      "1 tsp ghee",
      "Cucumber + onion salad",
    ],
    instructions: [
      "Toast cumin and bay leaf in ghee.",
      "Add onion and chickpeas; sauté 5 min.",
      "Fold in rice and warm through; serve with salad.",
    ],
    calories: 540, protein: 18, carbs: 88, fat: 12,
    servings: 1, prepTimeMins: 5, cookTimeMins: 15,
    regional: true,
  },
  {
    slug: "grilled-chicken-salad",
    title: "Grilled Chicken Salad",
    description: "Mixed-leaf salad with grilled chicken, cherry tomato, cucumber and olive oil.",
    categorySlug: "salads",
    tags: ["high-protein", "low-carb"],
    ingredients: [
      "150 g chicken breast",
      "2 cups mixed lettuce",
      "1/2 cup cherry tomatoes",
      "1/2 cucumber",
      "1 tbsp olive oil",
      "1 tbsp balsamic vinegar",
    ],
    instructions: [
      "Season and grill chicken 5 min each side; rest, then slice.",
      "Toss greens, tomato and cucumber with olive oil and balsamic.",
      "Top with chicken and serve.",
    ],
    calories: 380, protein: 42, carbs: 14, fat: 18,
    servings: 1, prepTimeMins: 10, cookTimeMins: 12,
    regional: false,
  },
  {
    slug: "tuna-pasta-salad",
    title: "Tuna Pasta Salad",
    description: "Cold pasta salad with canned tuna, sweetcorn, peppers and yogurt dressing.",
    categorySlug: "lunch",
    tags: ["high-protein"],
    ingredients: [
      "80 g whole-wheat pasta (dry)",
      "1 can tuna in water, drained",
      "1/4 cup sweetcorn",
      "1/2 red pepper, diced",
      "2 tbsp Greek yogurt",
      "1 tsp Dijon mustard",
    ],
    instructions: [
      "Boil pasta until al dente; cool under cold water.",
      "Mix yogurt and Dijon in a bowl.",
      "Combine pasta, tuna, sweetcorn and peppers; toss with dressing.",
    ],
    calories: 460, protein: 36, carbs: 58, fat: 8,
    servings: 1, prepTimeMins: 10, cookTimeMins: 10,
    regional: false,
  },
  {
    slug: "lentil-soup",
    title: "Lentil Soup",
    description: "Hearty red lentil soup with carrot, celery and cumin.",
    categorySlug: "soups",
    tags: ["vegetarian", "high-protein"],
    ingredients: [
      "3/4 cup red lentils",
      "1 carrot",
      "1 celery stalk",
      "1 small onion",
      "1 clove garlic",
      "1 tsp cumin",
      "4 cups vegetable stock",
      "1 tsp olive oil",
    ],
    instructions: [
      "Sauté onion, garlic, carrot and celery in oil 5 min.",
      "Add cumin, lentils and stock; simmer 20 min.",
      "Blend partially for a creamier texture; season and serve.",
    ],
    calories: 320, protein: 18, carbs: 50, fat: 4,
    servings: 1, prepTimeMins: 10, cookTimeMins: 25,
    regional: false,
  },
  {
    slug: "turkey-wrap",
    title: "Turkey & Hummus Wrap",
    description: "Wholewheat wrap with turkey, hummus, lettuce and tomato.",
    categorySlug: "lunch",
    tags: ["high-protein"],
    ingredients: [
      "1 large whole-wheat tortilla",
      "120 g turkey breast",
      "2 tbsp hummus",
      "1/2 cup lettuce",
      "1/2 tomato",
    ],
    instructions: [
      "Spread hummus across the tortilla.",
      "Layer turkey, lettuce and tomato.",
      "Roll tightly and slice in half.",
    ],
    calories: 420, protein: 36, carbs: 42, fat: 12,
    servings: 1, prepTimeMins: 5, cookTimeMins: 0,
    regional: false,
  },
  {
    slug: "haleem-portion",
    title: "Haleem (Portion-Controlled)",
    description: "Slow-cooked beef and lentil haleem with mint and lemon.",
    categorySlug: "lunch",
    tags: ["high-protein"],
    ingredients: [
      "150 g lean beef",
      "1/3 cup mixed lentils",
      "1 small onion",
      "1 tsp ginger-garlic",
      "1 tsp haleem masala",
      "Mint, lemon, fried onion for garnish",
    ],
    instructions: [
      "Pressure cook beef, lentils, onion, ginger-garlic and masala with water 25 min.",
      "Mash to a coarse paste; simmer 5 more min.",
      "Garnish with mint, lemon and fried onion.",
    ],
    calories: 480, protein: 38, carbs: 36, fat: 18,
    servings: 1, prepTimeMins: 10, cookTimeMins: 35,
    regional: true,
  },
  {
    slug: "chickpea-salad-bowl",
    title: "Chickpea Salad Bowl",
    description: "Cold chickpea bowl with cucumber, tomato, onion, lemon and olive oil.",
    categorySlug: "salads",
    tags: ["vegetarian", "high-protein"],
    ingredients: [
      "1 cup boiled chickpeas",
      "1 cucumber",
      "1 tomato",
      "1/2 small red onion",
      "2 tbsp lemon juice",
      "1 tbsp olive oil",
      "Mint leaves",
    ],
    instructions: [
      "Dice cucumber, tomato and onion.",
      "Toss with chickpeas, lemon, olive oil and mint.",
      "Chill 5 min before serving.",
    ],
    calories: 380, protein: 16, carbs: 50, fat: 14,
    servings: 1, prepTimeMins: 10, cookTimeMins: 0,
    regional: false,
  },
  {
    slug: "beef-keema-paratha",
    title: "Beef Keema with Paratha",
    description: "Lean minced beef cooked with peas, onion and spices, served with one paratha.",
    categorySlug: "lunch",
    tags: ["high-protein"],
    ingredients: [
      "150 g lean beef mince",
      "1/2 cup green peas",
      "1 onion",
      "1 tomato",
      "1 tsp ginger-garlic",
      "1 tsp coriander powder",
      "1 whole-wheat paratha",
    ],
    instructions: [
      "Sauté onion until golden; add ginger-garlic and tomato.",
      "Add mince and brown; stir in peas and spices.",
      "Simmer 10 min; serve with paratha.",
    ],
    calories: 520, protein: 38, carbs: 42, fat: 20,
    servings: 1, prepTimeMins: 10, cookTimeMins: 25,
    regional: true,
  },
  {
    slug: "veggie-fried-rice",
    title: "Veggie Fried Rice",
    description: "Quick fried rice with mixed vegetables, egg and a splash of soy sauce.",
    categorySlug: "lunch",
    tags: ["vegetarian"],
    ingredients: [
      "3/4 cup cooked basmati rice (chilled)",
      "1 egg",
      "1/2 cup mixed vegetables",
      "1 spring onion",
      "1 tbsp soy sauce",
      "1 tsp sesame oil",
    ],
    instructions: [
      "Heat sesame oil; scramble the egg and set aside.",
      "Stir-fry vegetables 2 min; add rice and soy sauce.",
      "Fold egg back in and finish with spring onion.",
    ],
    calories: 420, protein: 14, carbs: 62, fat: 12,
    servings: 1, prepTimeMins: 5, cookTimeMins: 8,
    regional: false,
  },
  {
    slug: "mediterranean-quinoa-bowl",
    title: "Mediterranean Quinoa Bowl",
    description: "Quinoa, chickpeas, feta, cucumber and lemon-oil dressing.",
    categorySlug: "lunch",
    tags: ["vegetarian", "high-protein"],
    ingredients: [
      "1/2 cup cooked quinoa",
      "1/2 cup chickpeas",
      "30 g feta",
      "1/2 cucumber",
      "Olives, parsley",
      "Lemon juice + olive oil",
    ],
    instructions: [
      "Layer quinoa, chickpeas, cucumber, olives and feta in a bowl.",
      "Drizzle with lemon juice and olive oil; finish with parsley.",
    ],
    calories: 430, protein: 18, carbs: 50, fat: 16,
    servings: 1, prepTimeMins: 10, cookTimeMins: 0,
    regional: false,
  },
  {
    slug: "chicken-tikka-roti",
    title: "Chicken Tikka with Roti",
    description: "Grilled chicken tikka pieces with two rotis and a side of mint chutney.",
    categorySlug: "lunch",
    tags: ["high-protein"],
    ingredients: [
      "200 g chicken breast",
      "2 tbsp yogurt",
      "1 tbsp tikka masala",
      "2 whole-wheat rotis",
      "Mint chutney + onions",
    ],
    instructions: [
      "Marinate chicken in yogurt and masala 30 min.",
      "Grill or pan-cook 5-6 min each side until charred.",
      "Serve with rotis, mint chutney and sliced onion.",
    ],
    calories: 540, protein: 50, carbs: 44, fat: 16,
    servings: 1, prepTimeMins: 30, cookTimeMins: 15,
    regional: true,
  },
  {
    slug: "fish-curry-rice",
    title: "Fish Curry with Rice",
    description: "Coconut-based fish curry served with half a cup of rice.",
    categorySlug: "lunch",
    tags: ["high-protein"],
    ingredients: [
      "180 g white fish fillet",
      "1/2 cup coconut milk",
      "1 onion",
      "1 tomato",
      "1 tsp curry powder",
      "1/2 cup cooked basmati rice",
    ],
    instructions: [
      "Sauté onion and tomato until soft.",
      "Add curry powder, coconut milk and 1/4 cup water; simmer 5 min.",
      "Slide in fish and poach 6-8 min; serve with rice.",
    ],
    calories: 460, protein: 36, carbs: 38, fat: 16,
    servings: 1, prepTimeMins: 10, cookTimeMins: 20,
    regional: true,
  },
];

// ─── Dinner (15) ───────────────────────────────────────────────────

const DINNER: RecipeDef[] = [
  {
    slug: "tandoori-chicken",
    title: "Tandoori Chicken",
    description: "Yogurt-marinated chicken roasted with garam masala and lemon.",
    categorySlug: "dinner",
    tags: ["high-protein", "low-carb"],
    ingredients: [
      "250 g bone-in chicken pieces",
      "3 tbsp yogurt",
      "1 tbsp tandoori masala",
      "1 tsp ginger-garlic paste",
      "Lemon juice",
    ],
    instructions: [
      "Marinate chicken in yogurt, masala, ginger-garlic and lemon for 1 hr.",
      "Bake at 220 °C for 25-30 min, turning once.",
      "Rest 5 min and serve with salad.",
    ],
    calories: 420, protein: 48, carbs: 6, fat: 22,
    servings: 1, prepTimeMins: 70, cookTimeMins: 30,
    regional: true,
  },
  {
    slug: "beef-nihari-portion",
    title: "Beef Nihari (Portion-Controlled)",
    description: "Slow-cooked beef nihari with bone marrow gravy, served with one naan.",
    categorySlug: "dinner",
    tags: ["high-protein"],
    ingredients: [
      "180 g lean beef shank",
      "1 tbsp nihari masala",
      "1 onion",
      "1 tsp ginger-garlic",
      "1 tbsp ghee",
      "1 small naan",
      "Lemon, ginger, coriander",
    ],
    instructions: [
      "Brown beef with onion and ginger-garlic in ghee.",
      "Stir in nihari masala and 2 cups water; pressure cook 35 min.",
      "Thicken gravy on stovetop; serve with naan, lemon and ginger.",
    ],
    calories: 580, protein: 38, carbs: 48, fat: 24,
    servings: 1, prepTimeMins: 10, cookTimeMins: 50,
    regional: true,
  },
  {
    slug: "grilled-salmon-veg",
    title: "Grilled Salmon with Vegetables",
    description: "Lemon-herb salmon with roasted broccoli and sweet potato.",
    categorySlug: "dinner",
    tags: ["high-protein", "gluten-free"],
    ingredients: [
      "180 g salmon fillet",
      "1 cup broccoli florets",
      "150 g sweet potato",
      "1 tbsp olive oil",
      "Lemon juice + herbs",
    ],
    instructions: [
      "Toss broccoli and sweet potato with olive oil; roast at 200 °C for 20 min.",
      "Grill salmon 4 min each side, finishing with lemon and herbs.",
      "Plate together and serve.",
    ],
    calories: 540, protein: 42, carbs: 38, fat: 22,
    servings: 1, prepTimeMins: 10, cookTimeMins: 20,
    regional: false,
  },
  {
    slug: "chicken-pulao",
    title: "Chicken Pulao",
    description: "Single-pot chicken pulao with whole spices and 3/4 cup rice.",
    categorySlug: "dinner",
    tags: ["high-protein"],
    ingredients: [
      "150 g chicken thigh",
      "3/4 cup basmati rice",
      "1 onion",
      "1 tsp ginger-garlic",
      "Whole garam masala",
      "1 tbsp oil",
    ],
    instructions: [
      "Brown onion in oil; add chicken, ginger-garlic and whole spices.",
      "Pour in rice and 1.25 cups water; bring to a boil.",
      "Cover and simmer 18 min; rest 5 min before serving.",
    ],
    calories: 540, protein: 38, carbs: 64, fat: 14,
    servings: 1, prepTimeMins: 10, cookTimeMins: 25,
    regional: true,
  },
  {
    slug: "palak-paneer",
    title: "Palak Paneer",
    description: "Spinach curry with home-style paneer cubes, served with one roti.",
    categorySlug: "dinner",
    tags: ["vegetarian", "high-protein"],
    ingredients: [
      "100 g paneer",
      "2 cups spinach",
      "1 onion",
      "1 tomato",
      "1 tsp ginger-garlic",
      "1 tsp garam masala",
      "1 roti",
    ],
    instructions: [
      "Blanch spinach; blend to a smooth purée.",
      "Sauté onion, tomato and ginger-garlic; stir in spinach and spices.",
      "Add paneer; simmer 5 min and serve with roti.",
    ],
    calories: 500, protein: 22, carbs: 36, fat: 28,
    servings: 1, prepTimeMins: 10, cookTimeMins: 20,
    regional: true,
  },
  {
    slug: "turkey-meatballs-zoodles",
    title: "Turkey Meatballs with Zoodles",
    description: "Lean turkey meatballs in tomato sauce over spiralised courgette.",
    categorySlug: "dinner",
    tags: ["high-protein", "low-carb"],
    ingredients: [
      "200 g lean turkey mince",
      "1 egg",
      "2 tbsp breadcrumbs",
      "1 cup tomato sauce",
      "1 large courgette (spiralised)",
      "1 tbsp olive oil",
    ],
    instructions: [
      "Mix turkey, egg and breadcrumbs; form 8 meatballs.",
      "Pan-fry in olive oil until browned; add sauce and simmer 8 min.",
      "Spiralise courgette, sauté 2 min and top with meatballs.",
    ],
    calories: 480, protein: 46, carbs: 22, fat: 22,
    servings: 1, prepTimeMins: 10, cookTimeMins: 20,
    regional: false,
  },
  {
    slug: "lamb-karahi",
    title: "Lamb Karahi",
    description: "Bone-in lamb cooked in tomato and ginger karahi style.",
    categorySlug: "dinner",
    tags: ["high-protein"],
    ingredients: [
      "200 g lamb shoulder",
      "2 tomatoes",
      "1 tbsp ginger-garlic",
      "1 tsp red chilli",
      "1 tbsp yogurt",
      "1 tbsp oil",
    ],
    instructions: [
      "Brown lamb in oil; add ginger-garlic.",
      "Stir in tomatoes, yogurt and spices; simmer 30 min until tender.",
      "Garnish with ginger and chilli; serve with roti.",
    ],
    calories: 560, protein: 44, carbs: 12, fat: 32,
    servings: 1, prepTimeMins: 10, cookTimeMins: 40,
    regional: true,
  },
  {
    slug: "shrimp-stir-fry",
    title: "Shrimp Stir-Fry",
    description: "Garlic-ginger prawn stir-fry with peppers and broccoli.",
    categorySlug: "dinner",
    tags: ["high-protein", "low-carb"],
    ingredients: [
      "200 g prawns",
      "1 red pepper",
      "1 cup broccoli",
      "1 tsp ginger",
      "2 cloves garlic",
      "1 tbsp soy sauce",
      "1 tsp sesame oil",
    ],
    instructions: [
      "Heat sesame oil; sauté ginger and garlic.",
      "Add prawns 2 min; toss in vegetables and soy sauce.",
      "Stir-fry 3 min; serve immediately.",
    ],
    calories: 320, protein: 38, carbs: 16, fat: 12,
    servings: 1, prepTimeMins: 10, cookTimeMins: 10,
    regional: false,
  },
  {
    slug: "chicken-handi",
    title: "Chicken Handi",
    description: "Creamy handi-style chicken with onion, tomato and cashew gravy.",
    categorySlug: "dinner",
    tags: ["high-protein"],
    ingredients: [
      "200 g chicken",
      "1 onion",
      "2 tomatoes",
      "1 tbsp cashew paste",
      "1 tsp ginger-garlic",
      "1 tbsp cream",
      "1 tsp garam masala",
    ],
    instructions: [
      "Brown onions; add ginger-garlic and tomatoes.",
      "Stir in cashew paste and chicken; cook 15 min.",
      "Finish with cream and garam masala.",
    ],
    calories: 520, protein: 38, carbs: 18, fat: 30,
    servings: 1, prepTimeMins: 10, cookTimeMins: 25,
    regional: true,
  },
  {
    slug: "baked-cod-veg",
    title: "Baked Cod with Vegetables",
    description: "Oven-baked cod fillet with lemon, garlic and seasonal vegetables.",
    categorySlug: "dinner",
    tags: ["high-protein", "low-carb"],
    ingredients: [
      "180 g cod fillet",
      "1 cup courgette + bell pepper",
      "2 garlic cloves",
      "1 tbsp olive oil",
      "Lemon, parsley",
    ],
    instructions: [
      "Place fish on foil with garlic, lemon and olive oil.",
      "Add vegetables; seal foil and bake at 200 °C for 18 min.",
      "Garnish with parsley.",
    ],
    calories: 360, protein: 38, carbs: 16, fat: 14,
    servings: 1, prepTimeMins: 10, cookTimeMins: 20,
    regional: false,
  },
  {
    slug: "saag-roti",
    title: "Saag with Roti",
    description: "Mustard-greens saag with one whole-wheat roti and a dollop of ghee.",
    categorySlug: "dinner",
    tags: ["vegetarian"],
    ingredients: [
      "2 cups mustard greens + spinach",
      "1 onion",
      "1 green chilli",
      "1 tsp ginger-garlic",
      "1 tbsp maize flour",
      "1 tsp ghee",
      "1 whole-wheat roti",
    ],
    instructions: [
      "Boil greens with onion and chilli; blend coarsely.",
      "Cook on low with ginger-garlic and maize flour until thick (10-15 min).",
      "Top with ghee and serve with roti.",
    ],
    calories: 380, protein: 12, carbs: 50, fat: 14,
    servings: 1, prepTimeMins: 15, cookTimeMins: 25,
    regional: true,
  },
  {
    slug: "lean-beef-stir-fry",
    title: "Lean Beef Stir-Fry",
    description: "Strips of lean beef stir-fried with onion, peppers and oyster sauce.",
    categorySlug: "dinner",
    tags: ["high-protein", "low-carb"],
    ingredients: [
      "180 g lean beef strips",
      "1 onion",
      "1 red pepper",
      "1 tbsp oyster sauce",
      "1 tsp ginger",
      "1 tsp sesame oil",
    ],
    instructions: [
      "Heat oil; sear beef 2 min and set aside.",
      "Sauté onion, pepper and ginger 3 min.",
      "Return beef, add oyster sauce, toss 1 min and serve.",
    ],
    calories: 420, protein: 38, carbs: 14, fat: 20,
    servings: 1, prepTimeMins: 10, cookTimeMins: 10,
    regional: false,
  },
  {
    slug: "veg-biryani-portion",
    title: "Vegetable Biryani (Portion-Controlled)",
    description: "Mixed-veg biryani with paneer, basmati rice and raita.",
    categorySlug: "dinner",
    tags: ["vegetarian"],
    ingredients: [
      "60 g paneer",
      "1 cup mixed vegetables",
      "3/4 cup basmati rice (cooked)",
      "1 tbsp biryani masala",
      "1 tsp ghee",
      "Raita",
    ],
    instructions: [
      "Sauté vegetables and paneer with masala in ghee.",
      "Layer over rice and steam 2 min.",
      "Serve with raita.",
    ],
    calories: 540, protein: 18, carbs: 78, fat: 18,
    servings: 1, prepTimeMins: 15, cookTimeMins: 25,
    regional: true,
  },
  {
    slug: "chicken-soup-noodles",
    title: "Chicken Soup with Noodles",
    description: "Light chicken broth with rice noodles, vegetables and shredded chicken.",
    categorySlug: "dinner",
    tags: ["high-protein"],
    ingredients: [
      "150 g chicken breast (cooked, shredded)",
      "60 g rice noodles",
      "3 cups chicken stock",
      "1 carrot, 1 spring onion, 1 garlic clove",
      "Soy sauce + lime",
    ],
    instructions: [
      "Simmer stock with garlic and carrot 5 min.",
      "Add noodles and cook 4 min; stir in chicken.",
      "Finish with soy and lime; top with spring onion.",
    ],
    calories: 380, protein: 36, carbs: 42, fat: 6,
    servings: 1, prepTimeMins: 5, cookTimeMins: 15,
    regional: false,
  },
  {
    slug: "egg-curry-roti",
    title: "Egg Curry with Roti",
    description: "Onion-tomato egg curry with two boiled eggs, served with one roti.",
    categorySlug: "dinner",
    tags: ["high-protein"],
    ingredients: [
      "2 boiled eggs",
      "1 onion, 1 tomato",
      "1 tsp ginger-garlic",
      "1 tsp curry powder",
      "1 tbsp oil",
      "1 whole-wheat roti",
    ],
    instructions: [
      "Sauté onion until golden; add ginger-garlic and tomato.",
      "Stir in curry powder and a splash of water; simmer 5 min.",
      "Slide in eggs and coat with gravy; serve with roti.",
    ],
    calories: 430, protein: 22, carbs: 36, fat: 22,
    servings: 1, prepTimeMins: 10, cookTimeMins: 15,
    regional: true,
  },
];

// ─── Snacks (8) ────────────────────────────────────────────────────

const SNACKS: RecipeDef[] = [
  {
    slug: "protein-shake",
    title: "Vanilla Whey Shake",
    description: "Quick shake with whey, banana and milk.",
    categorySlug: "snacks",
    tags: ["high-protein", "vegetarian"],
    ingredients: [
      "1 scoop vanilla whey",
      "1/2 banana",
      "250 ml semi-skimmed milk",
      "Ice cubes",
    ],
    instructions: [
      "Blend whey, banana and milk with ice 30 seconds.",
      "Serve cold.",
    ],
    calories: 280, protein: 32, carbs: 24, fat: 6,
    servings: 1, prepTimeMins: 3, cookTimeMins: 0,
    regional: false,
  },
  {
    slug: "fruit-yogurt-bowl",
    title: "Fruit & Yogurt Bowl",
    description: "200 g Greek yogurt with mixed seasonal fruit and a drizzle of honey.",
    categorySlug: "snacks",
    tags: ["vegetarian", "high-protein"],
    ingredients: [
      "200 g 0 % Greek yogurt",
      "1/2 cup mixed fruit",
      "1 tsp honey",
    ],
    instructions: [
      "Spoon yogurt into a bowl.",
      "Top with fruit and honey.",
    ],
    calories: 220, protein: 22, carbs: 26, fat: 2,
    servings: 1, prepTimeMins: 3, cookTimeMins: 0,
    regional: false,
  },
  {
    slug: "samosa-baked",
    title: "Baked Veg Samosa",
    description: "Two oven-baked vegetable samosas — lower fat than the fried version.",
    categorySlug: "snacks",
    tags: ["vegetarian"],
    ingredients: [
      "2 prepared samosa wrappers",
      "1/2 cup potato and pea filling",
      "Coriander chutney",
    ],
    instructions: [
      "Stuff wrappers with filling and seal with water.",
      "Brush with oil and bake at 200 °C for 15 min, flipping once.",
      "Serve with coriander chutney.",
    ],
    calories: 260, protein: 6, carbs: 38, fat: 8,
    servings: 1, prepTimeMins: 5, cookTimeMins: 15,
    regional: true,
  },
  {
    slug: "hummus-veggies",
    title: "Hummus with Veggie Sticks",
    description: "Carrot, cucumber and pepper sticks with 3 tbsp hummus.",
    categorySlug: "snacks",
    tags: ["vegetarian", "vegan"],
    ingredients: [
      "3 tbsp hummus",
      "1 carrot, sliced into sticks",
      "1/2 cucumber, sticks",
      "1/2 red pepper, sticks",
    ],
    instructions: [
      "Arrange vegetables on a plate.",
      "Serve with hummus.",
    ],
    calories: 180, protein: 6, carbs: 22, fat: 8,
    servings: 1, prepTimeMins: 5, cookTimeMins: 0,
    regional: false,
  },
  {
    slug: "chicken-shami-kebab",
    title: "Chicken Shami Kebab",
    description: "Two homemade chicken shami kebabs with mint chutney.",
    categorySlug: "snacks",
    tags: ["high-protein"],
    ingredients: [
      "150 g chicken mince",
      "1/4 cup chana daal (boiled)",
      "1 small onion",
      "1 green chilli",
      "Shami masala, salt",
      "1 tsp oil",
    ],
    instructions: [
      "Blend chicken, daal, onion, chilli and masala into a paste.",
      "Shape into two kebabs.",
      "Pan-fry in oil 3 min each side; serve with mint chutney.",
    ],
    calories: 280, protein: 28, carbs: 14, fat: 14,
    servings: 1, prepTimeMins: 10, cookTimeMins: 10,
    regional: true,
  },
  {
    slug: "apple-peanut-butter",
    title: "Apple & Peanut Butter",
    description: "Sliced apple with 1.5 tbsp peanut butter — easy filling snack.",
    categorySlug: "snacks",
    tags: ["vegetarian", "vegan"],
    ingredients: [
      "1 medium apple",
      "1.5 tbsp natural peanut butter",
    ],
    instructions: [
      "Slice apple into wedges.",
      "Serve with peanut butter for dipping.",
    ],
    calories: 230, protein: 6, carbs: 26, fat: 12,
    servings: 1, prepTimeMins: 3, cookTimeMins: 0,
    regional: false,
  },
  {
    slug: "boiled-eggs-and-fruit",
    title: "Boiled Eggs & Fruit",
    description: "Two boiled eggs with an orange — a portable high-protein snack.",
    categorySlug: "snacks",
    tags: ["high-protein", "gluten-free"],
    ingredients: [
      "2 large eggs",
      "1 orange",
      "Pinch of salt and pepper",
    ],
    instructions: [
      "Boil eggs 8 min, then plunge into cold water.",
      "Peel, season and serve with the orange.",
    ],
    calories: 220, protein: 14, carbs: 18, fat: 10,
    servings: 1, prepTimeMins: 2, cookTimeMins: 10,
    regional: false,
  },
  {
    slug: "rice-cakes-cottage-cheese",
    title: "Rice Cakes with Cottage Cheese",
    description: "Two rice cakes topped with cottage cheese, tomato and basil.",
    categorySlug: "snacks",
    tags: ["vegetarian", "high-protein"],
    ingredients: [
      "2 plain rice cakes",
      "1/3 cup low-fat cottage cheese",
      "Cherry tomatoes",
      "Fresh basil",
    ],
    instructions: [
      "Spread cottage cheese on rice cakes.",
      "Top with halved tomatoes and basil leaves.",
    ],
    calories: 170, protein: 12, carbs: 22, fat: 4,
    servings: 1, prepTimeMins: 3, cookTimeMins: 0,
    regional: false,
  },
];

// ─── Combined export ───────────────────────────────────────────────

export const SEED_RECIPES: RecipeDef[] = [
  ...BREAKFAST,
  ...LUNCH,
  ...DINNER,
  ...SNACKS,
];

// Sanity guard: 50 recipes per spec §6.
if (SEED_RECIPES.length !== 50) {
  throw new Error(
    `SEED_RECIPES must total 50 (got ${SEED_RECIPES.length})`
  );
}
